name: "ph285-project"
dependencies:
  - python=3.13
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipykernel # Required for running notebook cells in VS Code
  - ipympl # Provides matplotlib widget environment required to render animations in VS Code
  - nbconvert # Required for exporting notebooks as PDFs
